apiVersion: v2
appVersion: 4.24.0
dependencies:
- alias: postgresql
  condition: postgresql.deploy
  name: postgres
  repository: https://groundhog2k.github.io/helm-charts/
  version: 1.6.3
- alias: redis
  condition: redis.deploy
  name: valkey
  repository: https://valkey-io.github.io/valkey-helm
  version: 0.9.4
- alias: s3
  condition: s3.deploy
  name: seaweedfs
  repository: https://seaweedfs.github.io/seaweedfs/helm
  version: 4.23.0
description: Open source LLM engineering platform - LLM observability, metrics, evaluations,
  prompt management.
home: https://langfuse.com/
icon: https://langfuse.com/langfuse_logo.png
keywords:
- langfuse
- llm
- observability
- prompt management
- metrics
maintainers:
- email: contact@langfuse.com
  name: langfuse
  url: https://langfuse.com/
name: langfuse
sources:
- https://github.com/langfuse/langfuse
- https://github.com/langfuse/langfuse-k8s
type: application
version: 2.1.0
